config/routes.rb
Rails.application.routes.draw do
  get 'users/profile'

  devise_for :users

  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end

  get '/u/:id', to: 'users#profile', as: 'user'

  resources :posts do
    resources :comments
  end


  get 'home', to: "pages#home"
  get 'about', to: "pages#about"

  root 'posts#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_rich_text :body
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5, maximum: 100 }
  validates :body, presence: true, length: { minimum: 10, maximum: 9000 }
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable,
         :trackable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_account_update_params, if: :devise_controller?

  protected

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:create, :destroy, :update]
  before_action :set_comment, only: [:destroy, :update]

  def create
    @comment = @post.comments.create(comment_params)
    @comment.user = current_user

    if @comment.save
      flash[:notice] = "Comment was successfully created"
      redirect_to post_path(@comment)
    else
      flash[:alert] = "Comment was not created"
      redirect_to post_path(@post)
    end
  end

  def destroy
    @comment.destroy
  end

  def update
    if @comment.update(comment_params)
      format_html { redirect_to post_path(@post), notice: "Comment was successfully updated." }
    else
      format_html { redirect_to post_path(@post), alert: "Comment was not updated." }
    end

    redirect_to post_path(@comment)
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.update(views: @post.views + 1)
    @comments = @post.comments.order(created_at: :desc)
    puts("@comments.inpect: #{@comments.first.inspect}")
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :subtitle)
    end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  def profile
    @user.update(views: @user.views + 1)
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_form.html.erb
<%= form_with(model: [post, post.comments.build]) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mt-5 mb-2">
    <h5>Paste your thoughts</h5>
    <%= form.rich_text_area :body, class: "form-control" %>
  </div>

  <div>
    <%= form.submit "Reply", class: "btn btn-lg btn-success" %>
  </div>

<% end %>

app/views/comments/_index.html.erb
<div class="card-body p-4">
  <div class="d-flex flex-start">
    <img class="rounded-circle shadow-1-strong me-3"
         src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(26).webp" alt="avatar" width="60"
         height="60"/>
    <div class="w-100">
      <h6 class="fw-bold mb-1"><%= comment.user.name %>></h6>
      <div class="d-flex align-items-center mb-3">
        <span class="small mb-0">
          <%= time_ago_in_words(comment.created_at) %>
          <span class="badge bg-success">Approved</span>
        </span>
      </div>
      <p class="mb-0">
        <%= comment.body %>
      </p>

      <div class="d-flex gap-3 justify-content-end">
        <a href="#!" class="link-muted"><%= fa_icon "heart", class: "btn rounded btn-sm btn-warning text-white" %></a>
        <% if current_user == comment.user %>
          <%= button_to '', [post, comment], method: :delete, class: "btn rounded btn-sm btn-danger fa fa-trash text-white" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<hr class="my-0" style="height: 1px;"/>

app/views/layouts/_alerts.html.erb
<% if notice %>
  <p class="notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Blogger", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Blog", posts_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <%= render "components/session_manager" %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogDemo</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <%= javascript_include_tag "bootstrap-js/bootstrap.min" %>
</head>

<body>
<header>
  <%= render "layouts/navbar" %>
  <%= render "layouts/alerts" %>
</header>
<main class="container py-5">
  <%= yield %>
</main>
</body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <h1>About Me</h1>
  <p>Find me in <%= link_to "Go Home", root_path %></p>
</div>

app/views/pages/home.html.erb
<div class="container">
  <h1>My Personal Home</h1>
  <p>Find me in <%= link_to "Know me", about_path, class: "btn btn-secondary" %>,
  <%= link_to "Blogger", posts_path, class: "btn btn-primary" %></p>
</div>

app/views/posts/_article.html.erb
<header class="masthead" style="background: linear-gradient(lightblue,white)">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="post-heading">
          <h1><%= @post.title %></h1>
          <h2 class="subheading"><%= @post.subtitle || @post.body.truncate(27, separator: '...') %></h2>
          <span class="meta">
              Posted by
              <a href="#!"><%= @post.user.name || @post.user.email %></a>
              on <%= @post.created_at.to_fs %>
          </span>
        </div>
      </div>
    </div>
  </div>
</header>
<article class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <%= @post.body %>
      </div>
    </div>
  </div>
</article>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-4">
    <%= form.label :subtitle, class: "form-label" %>
    <%= form.text_field :subtitle, class: "form-control" %>
  </div>

  <div class="mb-4">
    <%= form.label :body, class: "form-label" %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div>
    <%= form.submit class: "btn btn-lg btn-success" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="post-preview">
  <%= link_to post do %>
    <h2 class="post-title"><%= post.title %></h2>
    <h3 class="post-subtitle"><%= (post.subtitle || post.body).truncate(79) %></h3>
  <% end %>
  <p class="post-meta">
    Posted by
    <a href="#!"><%= post.user.name || post.user.email %></a>
    on <%= post.created_at.to_fs %>
  </p>
</div>
<hr class="my-4"/>

app/views/posts/edit.html.erb
<div class="container">
  <h1>Editing post</h1>

  <%= render "form", post: @post %>

  <br>

  <div>
    <%= link_to "Show this post", @post, class: "btn btn-primary btn-sm" %>
    <%= link_to "Back to posts", posts_path, class: "btn btn-warning btn-sm" %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="d-flex justify-content-between">
    <h1>All Blogs</h1>
    <%= link_to "New post", new_post_path, class: "btn rounded btn-info" %>

  </div>

  <div id="posts">
    <% @posts.each do |post| %>
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
          <%= render post %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1>New post</h1>

  <%= render "form", post: @post %>

  <br>

  <div>
    <%= link_to "Back to posts", posts_path, class: "btn btn-warning btn-sm" %>
  </div>

</div>

app/views/posts/show.html.erb
<%= render "article" %>

<div class="d-flex gap-3 mb-3">
  <%= link_to "Edit this post", edit_post_path(@post), class: "btn btn-primary btn-sm" %>
  <%= link_to "Back to posts", posts_path, class: "btn btn-warning btn-sm" %>
</div>

<%= button_to "Destroy this post", @post, method: :delete, class: "btn btn-danger btn-sm" %>
<%= render "comments/form", post: @post %>

<div class="container my-5 py-5">
  <div class="row d-flex justify-content-center">
    <div class="col-md-12 col-lg-10">
      <div class="card text-dark rounded">
        <div class="card-body p-4">
          <h4 class="mb-0">Recent comments</h4>
          <p class="fw-light mb-4 pb-2">Latest Comments section by users</p>
        </div>
        <hr class="my-0" />
        <% @comments.each do |comment| %>
          <%= render "comments/index", post: @post, comment: comment %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<h1><%= @user.name %>></h1>
<h6> <%= pluralize @user.views, "views" %> </h6>